[profile.default]
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 300
via_ir = true
out = 'out'
test = 'test'
src = 'src'
libs = ['lib', 'node_modules']
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./addresses"}, { access = "read", path = "./chainConfigs"}, { access = "read", path = "./package.json" }]

[etherscan]
sepolia = { key = "$$ETHERSCAN_API_KEY" }
mainnet = { key = "$ETHERSCAN_API_KEY" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/1Rhy4iowYLfC12S86ZZaKUjy1tmLAars"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/qKOejal-tbfyH6_jIHxCGwExilHgqmbF"
